### ISSUE TITLE
filterable-listpicker inside a ScrollView

### ISSUE THREAD

**Issue by crowmagnumb** [nstudio/nativescript-plugins#5]
So I had my own homegrown version of this that popped up a modal dialog and that mostly works great but with one exception in which upon selection I was navigating to another page, but then the closing of the modal dialog also tried to reshow the page it was launched from and thus erasing the navigation I had just done. So I tried to make it "inline" but my data is inside of a ScrollView on the page and thus I couldn't scroll the ListView because the outer ScrollView took control.

So I found and tried this one and I get the exact same problem. :( First off I thought this was a modal dialog as seems to be implied by the gif and text, but it appears for me "inline" and I get the same problem that I can't control the ListView that shows because the outer ScrollView takes precedence.

Is there some way around this?

**Comment by crowmagnumb** [comment]
Wondering if there is any info you can give me here. I'm trying to push out a new release and this "bug' is holding me back.

**Comment by crowmagnumb** [comment]
OK, not sure why I didn't think of this before but I fixed my issue by putting my navigation in a setTimeout() so that the dialog closure reshowing of the current page happened in the current thread and then, later (I set the timeout to be like 200 milliseconds) my navigation happens. And that seems to work.

**Comment by davecoffin** [comment]
Great! Sorry I never responded this it must have floated to the bottom of my inbox. I'm glad you figured it out :)
