### ISSUE TITLE
Plugin: nativescript-tracking-transparency - Apple iOS ATT is not working on iOS 15

### ISSUE THREAD

**Issue by keithoys** [nstudio/nativescript-plugins#66]
Apparently, there could be a new API on iOS 15 for getting authorization status:

`class func requestTrackingAuthorization() async -> ATTrackingManager.AuthorizationStatus`

Please see: https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/3547037-requesttrackingauthorization

My implementation of this plugin was previously working and approved by Apple Team on iOS 14. However, Apple Team is rejecting it on iOS 15 terms now.

May I request @NathanWalker @triniwiz to review this plugin again please? Thank you.

**Comment by NathanWalker** [comment]
@keithoys thank you for the report, we’ll take a look on Monday.

**Comment by triniwiz** [comment]
Can you try moving the call to another location e.g login ?

**Comment by keithoys** [comment]
@triniwiz That does the trick! 💯 I moved the call from main.ts to Login page, and indeed solved the issue. Thank you!

**Comment by keithoys** [comment]
@triniwiz Can I understand how you'd figure this was the missing-link and root-cause in iOS 15?

**Comment by triniwiz** [comment]
The docs was the first place I checked but I also checked the other xplat repos they ran into the issue a couples before you did 🙂
