### ISSUE TITLE
Remove calling 'stop' on pausing the video

### ISSUE THREAD

**Issue by Brijeshlakkad** [nstudio/nativescript-plugins#7]
Hello guys,
These are great plugins. I was using @nstudio/nativescript-exoplayer, and I came to know that there is one issue. When user pauses the video, actually it is being stopped.

You can see the code at this line, [here](https://github.com/nstudio/nativescript-plugins/blob/70282786e139414e13c17bf961bae1c01ba03b92/packages/nativescript-exoplayer/index.android.ts#L395).

Please remove or comment this line. Because it is not letting the video play again, which is expected behaviour after stopping the video and unexpected behaviour to the people who does not know that the video is actually being stopped instead of pause.

Happy coding!

**Comment by natebgurutech** [comment]
I am also having this issue

**Comment by ZmanElete** [comment]
Hey there. I am running into this issue also. 

Any updates?

**Comment by Codex-** [comment]
Pull requests to resolve small findings like these make a huge difference! Please consider making a pull request with this change @natebgurutech @Brijeshlakkad

**Comment by NathanWalker** [comment]
Released with `5.0.6`
