### ISSUE TITLE
Error running demos: Cannot find module '@nstudio/nativescript-embrace/hooks/before-watchPatterns.js'

### ISSUE THREAD

**Issue by madmas** [nstudio/nativescript-plugins#82]
When trying to start the vue demo ap, I get the following error:

Cannot find module '@nstudio/nativescript-embrace/hooks/before-watchPatterns.js'

What I did:

- checkout repository
- `npm run setup`
- `npm start`
- select demo app to start

## env

`ns doctor `
✔ Getting environment information 

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 13.2.1 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 8.1.4 and the latest available version is 8.1.5.
✔ Component @nativescript/core has 8.1.5 version and is up to date.
✔ Component @nativescript/ios has 8.1.0 version and is up to date.
✔ Component @nativescript/android has 8.1.1 version and is up to date.

**Comment by triniwiz** [comment]
A little tip for anyone else that may run into the issue of running packages which contain hooks.

First you will need to build (can be found in the options after npm run start/ yarn start)  the offending packages in this instance it's `@nstudio/nativescript-embrace` after it's finished building update the demo package.json for the module to use the package from dist as follows

` "@nstudio/nativescript-embrace": "file:../../dist/packages/nativescript-embrace",`

This workspace has two plugins which make use of hooks so you would also need todo it for `nativescript-dynatrace` as well.
