### ISSUE TITLE
[nativescript-dynatrace] Plugin with id 'com.dynatrace.tools.android' not found

### ISSUE THREAD

**Issue by Z28ILOPE** [nstudio/nativescript-plugins#91]
I have added nativescript-dynatrace to my app and when I run de apllication, the terminal send me this error message:

```
* Where:
Build file '/Users/xxxxxx/code/myApp/platforms/android/build.gradle' line: 55

* What went wrong:
A problem occurred evaluating root project 'appdecathlon'.
> Plugin with id 'com.dynatrace.tools.android' not found.
```

Configuration:
Nativescript: 8.1.5
"@nativescript/android": "~8.1.1"

I've included this line in App_Resources/Android/app.gradle

`apply plugin:'com.dynatrace.tools.android'`

but the error continues

**Comment by Z28ILOPE** [comment]
This is a possible solution:

_**Maven Central in top-level gradle file**

Because the Dynatrace Android agent now requires the MavenCentral repository, if either jcenter() or mavenCentral() is not added inside of ALL the repositories blocks via the [top-level build.gradle](https://dt-url.net/jm610pso), the build will fail. Below is an example of what a basic [top-level build.gradle](https://dt-url.net/jm610pso) file should look like after adding mavenCentral() to all repository blocks:_
![nativescript-dynatrace](https://user-images.githubusercontent.com/95476334/165289367-8df178b2-2d3b-41ea-a40d-bc136e7b923b.png)

[https://www.npmjs.com/package/@dynatrace/react-native-plugin](url)

**Comment by triniwiz** [comment]
Try updating to the 8.2 runtime

**Comment by Z28ILOPE** [comment]
@triniwiz, I have tried it with runtime 8.2.3 and the error is persists.

**Comment by triniwiz** [comment]
MavenCentral has been added to the runtime
