### ISSUE TITLE
Exoplayer iOS 16 no controls 

### ISSUE THREAD

**Issue by kakha13** [nstudio/nativescript-plugins#94]
Can't get video controls inside GridLayout

**Comment by MayoudP** [comment]
Found a fixe by any chance ?

**Comment by kakha13** [comment]
> Found a fixe by any chance ?

Nope, made custom controls

**Comment by Tronix117** [comment]
That is a really blocking bug
Any help regarding on how to fix or bypass this issue ?

Seems related to : 
https://developer.apple.com/forums/thread/711360
https://stackoverflow.com/questions/73722242/avplayerviewcontroller-play-icon-removed-in-ios-16

Any official feedback (cc @NathanWalker) ?

**Comment by kakha13** [comment]
@triniwiz Thanks for fix. full screen video is working great but inside page controls does not appear
